/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import CreateQuestionMap from "./scripts/CreateQuestionMap"
import QuestionItem from "./scripts/QuestionItem"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="SetQuestionWindow.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scripts/CreateQuestionMap.ts",CreateQuestionMap);
        reg("scripts/QuestionItem.ts",QuestionItem);
    }
}
GameConfig.init();